layouts_dir: ./_layouts
title: ManKind Project Japan
description: We believe in building better men
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude: [
  exclude/, 
  Gemfile,
  Gemfile.lock,
  docker-compose.yml,
  LICENSE,
  README]
