version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll

  vscode:
    image: codercom/code-server
    command: --auth none
    ports:
      - 8080:8080
    volumes:
      - .:/home/coder/project